version: "3.8"
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api-gateway:
    image: yossef29/api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  articles-postgres:
    image: postgres:13.5
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-storage:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Change host port to avoid conflict

  articles:
    image: yossef29/articles
    environment:
      - DATABASE_URL=postgres://myuser:mypassword@articles-postgres:5432/median-db
    command: >
      sh -c "npx prisma db push && npm run start"
    ports:
      - "3000:3000"
    depends_on:
      - articles-postgres

volumes:
  postgres:
  postgres-storage:
